### ISSUE TITLE
My MATLAB reaches 71.3% baseline instead of 72.4%

### ISSUE THREAD

**Issue by lostanlen** [TUT-ARG/DCASE2016-baseline-system-matlab#1]
Hi,
I'm having trouble reproducing the baseline accuracies on my local machine, i.e. multicore Ubuntu with MATLAB 2013b. I'm running latest master on the repo.
Below are the results after calling the script task1_scene_classification:

![dcase_baseline](https://cloud.githubusercontent.com/assets/3943142/14139385/ffdc148c-f672-11e5-82d4-370a562ca0f8.jpg)

The above is consistent across runs, due to the re-initialization of the random seed.
This is not too bad of a failure, but since it is sensibly below the reported accuracy of 72.4%, I was worried if something might be wrong it my setup.

**Comment by toni-heittola** [comment]
Hi,

Your results are correct, 71.3 % is the correct overall performance for the task 1 baseline system. 

The number 72.4% to which you are referring was the reported performance number before commit aad58e14dc24300064360b124acec4933012b8bc. In this commit a bug in the evaluation was fixed, and the correct performance numbers were updated to the repository readme files, however, the task description page at DCASE2016 website was not apparently updated. This might have created the confusion with the right performance numbers. 

I have now fixed the DCASE2016 website to include correct performance numbers. 

-Toni
